#define screenWidth 1024
#define screenHeight 768

#define NOME_JOGO "O JOGO"

#define GRAVIDADE 500
#define JOGADOR_PULO_VELOCIDADE 500.0f
#define JOGADOR_MOVIMENTO_VELOCIDADE 500.0f

#define TAMANHO_X_JOGADOR 40 //40
#define TAMANHO_Y_JOGADOR 40 //132

//Constante Poder
#define PODER_MAX_PERSONAGEM 10
#define PODER_MOVIMENTO_VELOCIDADE 700


#define TAMANHO_X_CENARIO 3000
#define TAMANHO_Y_CENARIO 400

//Constantes referentes aos inimigos:

//Minions
#define TAMANHO_MINION_X 40 //56
#define TAMANHO_MINION_Y 40 //81

#define VELOCIDADE_INIMIGO_MINION 10.0f

//Gado:
#define TAMANHO_GADO_X 40 //110
#define TAMANHO_GADO_Y 40 //75


#define VELOCIDADE_INIMIGO_GADO_NORMAL 15.0f
#define VELOCIDADE_INIMIGO_GADO_STRESS 250.0f

//Habilidades:
#define RANGE_GADO 100