#define screenWidth 1024
#define screenHeight 768

#define NOME_JOGO "O JOGO"

#define GRAVIDADE 500
#define JOGADOR_PULO_VELOCIDADE 500.0f
#define JOGADOR_MOVIMENTO_VELOCIDADE 500.0f

#define TAMANHO_X_JOGADOR 40
#define TAMANHO_Y_JOGADOR 40

#define TAMANHO_X_CENARIO 2000
#define TAMANHO_Y_CENARIO 400